services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=udatakase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=mxuser'
    ports:
      - '3306'