spring:

  jpa:
    properties:
      hibernate:
        show_sql: false     # Log SQL statements
        format_sql: false   # Format SQL output in logs

#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create             # Generate database schema creation scripts
#              create-source: metadata             # Use entity metadata (JPA annotations) as the source for schema generation
#              drop-target: V1__init-mysql-database.sql    # File where the generated DROP schema script will be written
#              create-target: V1__init-mysql-database.sql  # File where the generated CREATE schema script will be written

  flyway:
    enabled: false

  docker:
    compose:
      enabled: false